plot(x = data$Date_Time,y=data$Sub_metering_1,type = "n",xlab=NA,ylab = "Energy sub metering")
lines(x = data$Date_Time,y=data$Sub_metering_1)
lines(x = data$Date_Time,y=data$Sub_metering_2, col="red")
lines(x = data$Date_Time,y=data$Sub_metering_3, col="blue")
legend("topright", lty = 1, lwd=1, col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))